import Head from 'next/head';
import react from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Footer from '../../../shared/components/footer';
import Nav from '../../../shared/components/navigation';
import BottomNav from '../components/bottomNav';
import ClubSection from '../components/clubbSection';
import Banner from '../components/homepageBanner';
import PlayerSection from '../components/playerSection';
import SponsorSection from '../components/sponsorSection';



const sectionPadding = {
	margin: 'auto',
};

export default function HomePage() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Project examne</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className="homepage_layout">
				<Nav />
				<section id="top" className='banner'>
					<Banner />
				</section>
				<section style={sectionPadding}>
					<SponsorSection />
				</section>
				<section id='forSpillere' style={sectionPadding}>
					<PlayerSection />
				</section>
				<section id='forKlubber'>
					<ClubSection />
				</section>
					<BottomNav />
				<section>
					<Footer />
				</section>
				
			</main>
		</div>
	);
}
