/*import Link from 'next/link';
import Head from 'next/head';
import Nav from '../../src/components/navigation/navigation';
//import Product, { base_url } from './products/productFetch';
import axios from 'axios';

const product_layout = {
	display: 'flex',
	flexDirection: 'row',
	flexWrap: 'wrap',
	justifyContent: 'space-between',
	backgroundColor: '#ECECEC',
	minHeight: '100vh',
	padding: '2rem',
};

export const getServerSideProps = async (ctx) => {
	const res = await axios.get(base_url);
	console.log(res.data);
	const products = res.data.data;
	return { props: { products: res.data } };
};

export default function Products({ products }) {
	console.log(products);
	return (
		<div>
			<Head>
				<title>våre produkter</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Nav />
			<main style={product_layout}>
				{products.data.map((product) => {
					return (
						<div className='card' key={product.id}>
							<section className='front'>
								<h3 className='card_title'>{product.attributes.name}</h3>
								<p className='card_dimensions'>
									{product.attributes.dimensjoner}
								</p>
							</section>
							<section className='back'>
								<h3 className='card_title_flipped'>
									{product.attributes.name}
								</h3>
								<p className='card_dimensions_flipped'>
									{product.attributes.dimensjoner}
								</p>
							</section>
						</div>
					);
				})}
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const product = await fetch(base_url).then((r) => r.json());
	console.log(product);
	return {
		props: {
			product,
		},
	};
}
*/
import type { InferGetStaticPropsType } from 'next'
import { ProductResponse } from '../../src/components/stuff/response'
import Nav from '../../src/components/navigation/navigation'
import { STRAPI_API } from './consts'
import Link from "next/link"


export default function Home({
	products,
}: InferGetStaticPropsType<typeof getStaticProps>) {
	return (
		<main>
			<div>
				<h2>Hello there</h2>
			</div>
			
			<div className='product_layout'>
				{products.map((product) => {
					return (
						<div className='#' key={product.id}>
							<section className='#'>
								<h3 className='card_title'>{product.attributes.name}</h3>
								<p className='card_dimensions'>
									{product.attributes.dimensjoner}
								</p>
								<Link href={`/products/${product.id}`}>
									<a className="#">
                
										<h3 className="#">
											{product.attributes.name}
										</h3>
										<p>{product.attributes.description}</p>
									</a>
								</Link>
							</section>
						</div>
					)
				})}
			</div>
		</main>
	)
};
				



export async function getStaticProps() {
		const response = await fetch(`${STRAPI_API}/api/products`)

		if (!response.ok) {
			throw new Error(await response.text())
		}

		const products: ProductResponse = await response.json()
		return {
			props: {
				products: products.data,
			},
		}
	}
;

{/* 		<section className='back'>
								<h3 className='card_title_flipped'>
									{product.attributes.name}
								</h3>
								<p className='card_dimensions_flipped'>
									{product.attributes.dimensjoner}
								</p> */}
							
						{/* </section> */}