import Head from 'next/head';
import Nav from '../src/components/navigation/navigation';

import Image from 'next/image';

const contact_layout = {
	minHeight: '100vh',
	width: '100%',
	display: 'flex',
	flexDirection: 'column',
};
const contact_left_container = {
	width: '100%',
};
const contact_form_container = {
	width: '100%',
	backGroundColor: 'var(--secondary-color)',
};
const contact_title = {
	textAlign: 'center',
};
export default function Contact() {
	return (
		<div>
			<Head>
				<title>Contact us</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main style={contact_layout}>
				<h1 style={contact_title}>contact us</h1>
				<div style={{ display: 'flex', flexDirection: 'row' }}>
					<div
						className='contact_left_container'
						style={contact_left_container}></div>
					<div style={contact_form_container}></div>
				</div>
			</main>
		</div>
	);
}
