import Head from 'next/head';
import Image from 'next/image';

const contact_layout = {
	minHeight: '100vh',
	width: '100%',
	display: 'flex',
	flexDirection: 'row',
};
const contact_left_container = {
	width: '100%',
};
const contact_form_container = {
	width: '100%',
};
const contact_title = {
	textAlign: 'center',
};
export default function Contact() {
	return (
		<div>
			<Head>
				<title>Contact us</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main style={contact_layout}>
				<div>
					<div
						className='contact_left_container'
						style={contact_left_container}>
						<h2>Hello there</h2>
					</div>
					<div className='cotact_left_container' style={contact_form_container}>
						<h2 style={contact_title}>Kontakt oss</h2>
					</div>
				</div>
			</main>
		</div>
	);
}
