import Head from 'next/head';
import Nav from '../src/components/navigation/navigation';

export default function Contact() {
	return (
		<div>
			<Head>
				<title>Contact us</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Nav />
			<main>
				<h1>contact us</h1>
			</main>
		</div>
	);
}
