import Head from 'next/head';
import react from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import SponsorSection from '../src/components/homePage/sponsorSection.js';
import PlayerSection from '../src/components/homePage/playerSection.js';
import ClubSection from '../src/components/homePage/clubbSection.js';
import Nav from '../src/components/navigation/navigation.js';
//import Product from '../src/components/productFetch';
//import axios from 'axios';
import Banner from '../src/components/homePage/homepageBanner';
import Footer from '../src/components/footer/footer.js';

const mainLayout = {
	display: 'flex',
	flexDirection: 'column',
	justifyContent: 'center',
	padding: '0rem',
	backgroundColor: '#ECECEC',
};
const sectionPadding = {
	margin: 'auto',
};

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Project examne</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main style={mainLayout}>
				<Nav />
				<section className='banner'>
					<Banner />
				</section>

				<section style={sectionPadding}>
					<SponsorSection />
				</section>
				<section id='forSpillere' style={sectionPadding}>
					<PlayerSection />
				</section>
				<section id='forKlubber'>
					<ClubSection />
				</section>
				<Footer />
			</main>
		</div>
	);
}
