import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import SponsorSection from '../src/components/homePage/sponsorSection.js';
import PlayerSection from '../src/components/homePage/playerSection.js';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Project examne</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main>
				<SponsorSection />
				<PlayerSection />
			</main>
		</div>
	);
}
