import Head from 'next/head';
import react from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import SponsorSection from '../src/components/homePage/sponsorSection';
import PlayerSection from '../src/components/homePage/playerSection';
import ClubSection from '../src/components/homePage/clubbSection';
import Nav from '../src/components/navigation/navigation';
import Banner from '../src/components/homePage/homepageBanner';
import Footer from '../src/components/footer/footer';


const sectionPadding = {
	margin: 'auto',
};

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Project examne</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main className="homepage_layout">
				<Nav />
				<section className='banner'>
					<Banner />
				</section>

				<section style={sectionPadding}>
					<SponsorSection />
				</section>
				<section id='forSpillere' style={sectionPadding}>
					<PlayerSection />
				</section>
				<section id='forKlubber'>
					<ClubSection />
				</section>
				<div className='bottom_layer'><button>Login</button></div>
				<section>
					<Footer />
				</section>
			</main>
		</div>
	);
}
