import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import SponsorSection from '../src/components/homePage/sponsorSection.js';
import PlayerSection from '../src/components/homePage/playerSection.js';
import ClubSection from '../src/components/homePage/clubbSection.js';
import { faColumns } from '@fortawesome/free-solid-svg-icons';

const mainLayout = {
	display: 'flex',
	flexDirection: 'column',
	justifyContent: 'center',
	padding: '0rem',
};
const sectionPadding = {
	margin: 'auto',
};

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Project examne</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<main style={mainLayout}>
				<section>
					<SponsorSection />
				</section>
				<section style={sectionPadding}>
					<PlayerSection />
				</section>
				<section>
					<ClubSection />
				</section>
			</main>
		</div>
	);
}
