import Head from 'next/head';
import Nav from '../src/components/navigation/navigation';
import Product, { base_url } from './products/productFetch.js';
import { goalRender } from './api/index';
import axios from 'axios';

const product_layout = {
	display: 'flex',
	flexDirection: 'row',
	flexWrap: 'wrap',
	justifyContent: 'space-between',
	backgroundColor: '#ECECEC',
	minHeight: '100vh',
	padding: '2rem',
};

export const getServerSideProps = async (ctx) => {
	const res = await axios.get(base_url);
	console.log(res.data);
	const products = res.data.data;
	return { props: { products: res.data } };
};

export default function Products({ products }) {
	console.log(products);
	return (
		<div>
			<Head>
				<title>våre produkter</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Nav />
			<main style={product_layout}>
				{products.data.map((product) => {
					return (
						<div className='card' key={product.id}>
							<section className='front'>
								<h3 className='card_title'>{product.attributes.name}</h3>
								<p className='card_dimensions'>
									{product.attributes.dimensjoner}
								</p>
							</section>
							<section className='back'>
								<h3 className='card_title_flipped'>
									{product.attributes.name}
								</h3>
								<p className='card_dimensions_flipped'>
									{product.attributes.dimensjoner}
								</p>
							</section>
						</div>
					);
				})}
			</main>
		</div>
	);
}
/*<div className='product_card' key={product.id}>
							<div className='text_container'>
								<h3 className='card_title'>{product.attributes.name}</h3>
								<p className='card_dimensions'>
									{product.attributes.dimensjoner}
								</p>
							</div>
						</div>
						
						
						
						<div className='flip-card' key={product.id}>
							<div className='flip-card-inner'>
								<div className='flip-card-front'>
									<img
										src='https://www.w3schools.com/howto/img_avatar.png'
										alt='Avatar'
									/>

									<div className='text_container'>
										<h3 className='card_title'>{product.attributes.name}</h3>
										<p className='card_dimensions'>
											{product.attributes.dimensjoner}
										</p>
									</div>
								</div>
								<div className='flip-card-back'>
									<h3 className='card_title_flipped'>
										{product.attributes.name}
									</h3>
									<p className='card_dimensions_flipped'>
										{product.attributes.dimensjoner}
									</p>
									<p>We love that guy</p>
								</div>
							</div>
						</div>
						
						
						
						
						*/
