import Head from 'next/head';
import Nav from '../src/components/navigation/navigation';
import Product from './products/productFetch.js';
import { goalRender } from './api/index';
import axios from 'axios';

const product_layout = {
	display: 'flex',
	flexDirection: 'row',
	flexWrap: 'wrap',
	backgroundColor: '#ECECEC',
	minHeight: '100vh',
};

export const getServerSideProps = async (ctx) => {
	const res = await axios.get('http://localhost:1337/api/products');
	console.log(res.data);
	const products = res.data.data;
	return { props: { products: res.data } };
};

export default function Products({ products }) {
	console.log(products);
	return (
		<div>
			<Head>
				<title>våre produkter</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Nav />
			<main style={product_layout}>
				<h1>Products</h1>
				{products.data.map((product) => {
					return (
						<div key={product.id}>
							<h3>{product.attributes.name}</h3>
							<p>{product.attributes.description}</p>
							<p>{product.attributes.info}</p>
						</div>
					);
				})}
			</main>
		</div>
	);
}
